### ISSUE TITLE
5. SQL Analytics with Spark

### ISSUE THREAD

**Issue by floflokie** [Alhuuin/Big-Data-LaChouffe#4]
**Task**: Use Spark SQL to perform advanced queries on the cleaned dataset. Examples include:

- [ ]  Finding top customers by total spend.
- [ ] Analyzing purchase frequency by customer segment.
- [ ] Identifying trends in product purchases over time.
